export const FETCH_LOOKUP = 'FETCH_LOOKUP'
export const FETCH_LOOKUP_SUCCESS = 'FETCH_LOOKUP_SUCCESS'
export const FETCH_LOOKUP_FAILURE = 'FETCH_LOOKUP_FAILURE'
export const UPDATE_LOOKUP = 'UPDATE_LOOKUP'
export const LOGOUT = 'LOGOUT'


export const FETCH_LOOKUPUSER = 'FETCH_LOOKUPUSER'
export const FETCH_LOOKUPUSER_SUCCESS = 'FETCH_LOOKUPUSER_SUCCESS'
export const FETCH_LOOKUPUSER_FAILURE = 'FETCH_LOOKUPUSER_FAILURE'
export const UPDATE_LOOKUPUSER = 'UPDATE_LOOKUPUSER'