// auth.js
export const FETCH_ACL = 'FETCH_ACL'
export const FETCH_ACL_SUCCESS = 'FETCH_ACL_SUCCESS'
export const FETCH_ACL_FAILURE = 'FETCH_ACL_FAILURE'
export const UPDATE_ACL = 'UPDATE_ACL'


export const FETCH_ROLE = 'FETCH_ROLE'
export const FETCH_ROLE_SUCCESS = 'FETCH_ROLE_SUCCESS'
export const FETCH_ROLE_FAILURE = 'FETCH_ROLE_FAILURE'
export const UPDATE_ROLE = 'UPDATE_ROLE'


export const FETCH_PERMISSION = 'FETCH_PERMISSION'
export const FETCH_PERMISSION_SUCCESS = 'FETCH_PERMISSION_SUCCESS'
export const FETCH_PERMISSION_FAILURE = 'FETCH_PERMISSION_FAILURE'
export const UPDATE_PERMISSION = 'UPDATE_PERMISSION'


export const LOGOUT = 'LOGOUT'