// auth.js
export const FETCH_BRANCH = 'FETCH_BRANCH'
export const FETCH_BRANCH_SUCCESS = 'FETCH_BRANCH_SUCCESS'
export const FETCH_BRANCH_FAILURE = 'FETCH_BRANCH_FAILURE'
export const UPDATE_BRANCH = 'UPDATE_BRANCH'
export const UPDATE_MYBRANCH = 'UPDATE_MYBRANCH'


export const LOGOUT = 'LOGOUT'